# Generated by Django 5.1.6 on 2025-02-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
