# Generated by Django 5.1.6 on 2025-02-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_facturacion', '0002_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='customer_dni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_facturacion.customers'),
        ),
    ]
