# Generated by Django 5.1.6 on 2025-02-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_facturacion', '0003_products_customer_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='customer_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_facturacion.customers'),
        ),
    ]
