# Generated by Django 5.1.6 on 2025-02-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_facturacion', '0004_alter_products_customer_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
